// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjGQR2HxXzdudJGRsY3U4AGDrukiZWnDM',
    appId: '1:1034911722091:web:f8ff5cddaabf535d7e1f2e',
    messagingSenderId: '1034911722091',
    projectId: 'lsu-csc3380-project-fall-2025',
    authDomain: 'lsu-csc3380-project-fall-2025.firebaseapp.com',
    storageBucket: 'lsu-csc3380-project-fall-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeYlKHyzg7R3yJtrSQNANrvnwT9wkyNoQ',
    appId: '1:1034911722091:android:c86e0cf734fe7fba7e1f2e',
    messagingSenderId: '1034911722091',
    projectId: 'lsu-csc3380-project-fall-2025',
    storageBucket: 'lsu-csc3380-project-fall-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6nGdy28Lkvx5lLpZP1Z0eidRkL-dE4YY',
    appId: '1:1034911722091:ios:37b5c2f79b389c257e1f2e',
    messagingSenderId: '1034911722091',
    projectId: 'lsu-csc3380-project-fall-2025',
    storageBucket: 'lsu-csc3380-project-fall-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6nGdy28Lkvx5lLpZP1Z0eidRkL-dE4YY',
    appId: '1:1034911722091:ios:37b5c2f79b389c257e1f2e',
    messagingSenderId: '1034911722091',
    projectId: 'lsu-csc3380-project-fall-2025',
    storageBucket: 'lsu-csc3380-project-fall-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

}